name: Devolution Deployment

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest
        environment: devolution-studio

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Dependencies
              run: npm install

            - name: Project build
              run: |
                  npm run build

            - name: Env file
              run: |
                  echo "HOST=devolution.studio" >> ./dist/.env
                  echo "PORT=8081" >> ./dist/.env
                  echo "ENV=prod" >> ./dist/.env
                  echo "CGV_LAST_UPDATE=19/02/2023" >> ./dist/.env
                  echo "MAIL_USER_TO=${{ secrets.MAIL_USER_TO }}" >> ./dist/.env
                  echo "MAIL_USER=${{ secrets.MAIL_USER }}" >> ./dist/.env
                  echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> ./dist/.env
                  echo "RECAPTCHA_CLIENT_KEY=${{ secrets.RECAPTCHA_CLIENT_KEY }}" >> ./dist/.env
                  echo "RECAPTCHA_SERVER_KEY=${{ secrets.RECAPTCHA_SERVER_KEY }}" >> ./dist/.env

            - name: Artifact upload
              uses: actions/upload-artifact@main
              with:
                  name: dist-artifact
                  path: dist/

            - name: Deploy
              uses: easingthemes/ssh-deploy@main
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  ARGS: '-rlgoDzvc -i'
                  SOURCE: 'dist/'
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  TARGET: ${{ secrets.REMOTE_TARGET }}
                  EXCLUDE: '/node_modules/'
                  SCRIPT_AFTER: |
                      export PATH=$PATH:${{ secrets.REMOTE_NODE_BIN_FOLDER }}
                      cd ${{ secrets.REMOTE_TARGET }}
                      npm i
                      pm2 stop devolution2 -s
                      pm2 start ./server/server.js --name devolution2 -s
